version: '3.7'
services:
  # db:
  #   container_name: db
  #   image: postgres:12.9
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: sai_db
  #   volumes:
  #     - database-data:/var/lib/postgresql/data
  #   restart: always

  sai-backend:
    container_name: sai-backend
    image: sai-backend
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # links:
    #   - db
    # depends_on:
    #   - db
    restart: always

# volumes:
#   database-data:
  # pd-data:
